### PR TITLE
Building Develop fail due to Nginx and update related to Ubuntu Base Upgrade

### PR DESCRIPTION
**Pull request by IslamAlam**
**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] New Feature
- [x] Feature Improvment
- [ ] Refactoring
- [ ] Documentation
- [x] Other, please describe:

**Description:**

Currently installing Flair via pip fail during the build of the latest develop-branch.

        Requirement already satisfied, skipping upgrade: ipython-genutils==0.2.0 in /opt/conda/lib/python3.7/site-packages (from flair==0.4.4->-r /resources/libraries/requirements-full.txt (line 98)) (0.2.0)
        Collecting sqlitedict>=1.6.0
        Downloading https://files.pythonhosted.org/packages/0f/1c/c757b93147a219cf1e25cef7e1ad9b595b7f802159493c45ce116521caff/sqlitedict-1.6.0.tar.gz
        Collecting tiny-tokenizer[all]
        Downloading https://files.pythonhosted.org/packages/8d/0f/aa52c227c5af69914be05723b3deaf221805a4ccbce87643194ef2cdde43/tiny_tokenizer-3.1.0.tar.gz
        [91mERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
        tiny-tokenizer depends on SudachiDict_core@ https://object-storage.tyo2.conoha.io/v1/nc_2520839e1f9641b08211a5c85243124a/sudachi/SudachiDict_core-20190927.tar.gz 
        [0mThe command '/bin/sh -c ln -s -f $CONDA_DIR/bin/python /usr/bin/python &&     apt-get update &&     pip install --upgrade pip &&     if [ "$WORKSPACE_FLAVOR" = "minimal" ]; then         conda install -y --update-all nomkl ;     else         conda install -y --update-all mkl ;     fi &&     conda install -y --update-all             'python='$PYTHON_VERSION             tqdm             pyzmq             cython             graphviz             numpy             matplotlib             scipy             requests             urllib3             pandas             six             future             protobuf             zlib             boost             psutil             PyYAML             python-crontab             ipykernel             cmake             Pillow             'ipython=7.10.*'             'notebook=6.0.*'             'jupyterlab=1.2.*' &&     pip install --no-cache-dir --upgrade -r ${RESOURCES_PATH}/libraries/requirements-minimal.txt &&     if [ "$WORKSPACE_FLAVOR" = "minimal" ]; then         fix-permissions.sh $CONDA_DIR &&         clean-layer.sh &&         exit 0 ;     fi &&     apt-get install -y --no-install-recommends libopenmpi-dev openmpi-bin &&     conda install -y mkl-include &&     conda install -y numba &&     conda install -y 'tensorflow=2.0.*' &&     conda install -y -c pytorch "pytorch==1.3.*" torchvision cpuonly &&     pip install --no-cache-dir --upgrade -r ${RESOURCES_PATH}/libraries/requirements-light.txt &&     if [ "$WORKSPACE_FLAVOR" = "light" ]; then         fix-permissions.sh $CONDA_DIR &&         clean-layer.sh &&         exit 0 ;     fi &&     apt-get install -y --no-install-recommends liblapack-dev libatlas-base-dev libeigen3-dev pandoc libblas-dev &&     conda install -y -c pytorch faiss-cpu &&     pip install --no-cache-dir --upgrade -r ${RESOURCES_PATH}/libraries/requirements-full.txt &&     python -m spacy download en &&     cd $CONDA_PYTHON_DIR/site-packages/spacy/lang &&     rm -rf tr pt da sv ca nb &&     fix-permissions.sh $CONDA_DIR &&     clean-layer.sh' returned a non-zero code: 1
        Executing: docker build -t ml-workspace:latest -t ml-workspace:latest  --build-arg ARG_WORKSPACE_VERSION=latest  --build-arg ARG_WORKSPACE_FLAVOR=full  --build-arg ARG_VCS_REF=8242e6b  --build-arg ARG_BUILD_DATE=2020-01-01T12:27:14Z ./
        Failed to build container

The workaround is mentioned [here](https://github.com/flairNLP/flair/issues/1327).

**Checklist:**

- [x] I have read the [CONTRIBUTING](https://github.com/ml-tooling/ml-workspace/blob/master/CONTRIBUTING.md) document.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

* Fix issues related to the build of Openresty, Nginx, and OpenSSL
* Upgrading CUDA, apt packages for ubuntu 18.04

The docker files have been built and tested:
https://hub.docker.com/u/imansour

### CODE REVIEW

**Comment by ffarella** [comment]
Hi!
You need to fallback to filebrowser==v2.0.16 !
The new version (modified 10days ago) doesnt work.
At least for me

```bash
install_path="/usr/local/bin"
filemanager_bin="filebrowser"
filemanager_file="linux-amd64-filebrowser.tar.gz"
filemanager_url="https://github.com/filebrowser/filebrowser/releases/download/v2.0.16/linux-amd64-filebrowser.tar.gz"
rm -rf "/tmp/$filemanager_file"
wget  "$filemanager_url" -O "/tmp/$filemanager_file"
tar -xzf "/tmp/$filemanager_file" -C "/tmp/" "$filemanager_bin"
chmod +x "/tmp/$filemanager_bin"
echo "Putting filemanager in $install_path (may require password)"
mv "/tmp/$filemanager_bin" "$install_path/$filemanager_bin"
```

**Comment by lukasmasuch** [comment]
Thanks for the Pull Request :+1: I'm planning to merge it soon, but I'm unsure about the changes for OpenResty/Nginx/OpenSSL. The current way of installing those tools is working fine for me. Do you have more information on the issue you had with those tools?

**Comment by IslamAlam** [comment]
@LukasMasuch When I built the latest image from you branch Nginx was not able to start due to  this error:

`/usr/local/nginx/sbin/nginx: symbol lookup error: /usr/local/nginx/sbin/nginx: undefined symbol: lua_getexdata
`

After more analysis, I found that Nginx was pointing to the wrong library in the default library path:
`libluajit-5.1.so.2 => /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2 (0x00007f0db9170000) 
`

This was causing Nginx to fail to start. Then I found the best way to resolve this issue to build OpenResty, OpenSSL, and Luajit from source together because [OpenSSL is patched by OpenResty Link ](https://openresty.org/en/openssl-patches.html).

Before:

    $ ldd /usr/local/openresty/nginx/sbin/nginx 
        linux-vdso.so.1 (0x00007ffd4b4f3000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0db9840000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0db9621000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f0db93e9000)
        libluajit-5.1.so.2 => /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2 (0x00007f0db9170000)
        libpcre.so.1 => /opt/conda/lib/libpcre.so.1 (0x00007f0dba02c000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f0db8ee3000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f0db8a18000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0db87fb000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0db840a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0db9e4f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0db806c000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0db7e54000)


Now:

    $ ldd /usr/local/openresty/nginx/sbin/nginx
        linux-vdso.so.1 (0x00007ffd9b36b000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0f4f931000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0f4f712000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f0f4f4da000)
        libluajit-5.1.so.2 => /usr/local/openresty/luajit/lib/libluajit-5.1.so.2 (0x00007f0f4f259000)
        libpcre.so.1 => /usr/local/openresty/pcre/lib/libpcre.so.1 (0x00007f0f4efe7000)
        libssl.so.1.1 => /usr/local/openresty/openssl/lib/libssl.so.1.1 (0x00007f0f4ed52000)
        libcrypto.so.1.1 => /usr/local/openresty/openssl/lib/libcrypto.so.1.1 (0x00007f0f4e85f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0f4e642000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0f4e251000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0f4ff3f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0f4deb3000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0f4dc9b000)

So Nginx is pointing now to the correct library which is patched by Openresty.

**Comment by IslamAlam** [comment]
@LukasMasuch would you recommend keeping cuda-10.1 or upgrading to cuda-10.2?

**Comment by lukasmasuch** [comment]
After doing a clean build, I also stumbled on the same problem with OpenResty. The issue came from the installation of pandoc which I removed for now (it's installed via conda anyways). With the current develop branch, the workspace should be fully buildable again without building OpenResty from source.

Regarding CUDA: I decided to update from CUDA 10.0 to 10.1 since 10.2 is, unfortunately, not yet supported with many frameworks (e.g. tensorflow/pytorch).

Thanks again for your contributions! I tried to apply all the fixes within this pull request to the current workspace version (check out the current develop branch), there are also some new docker images pushed: `docker pull mltooling/ml-workspace:0.9.0-SNAPSHOT`. Unfortunately, I wasn't able to merge this Pull Request since I decided to go for the OpenResty binaries and CUDA 10.1.

Btw. I plan to release a new stable version probably tomorrow.

**Comment by IslamAlam** [comment]
@LukasMasuch thanks so much for your efforts and time both ml-workspace and ml-hub are extremely good. 
I will close then the PR.

**Pull request closed without merging**
