### PR TITLE
ENH: Add datalad installation via conda

### LINKED ISSUE #50: Add DataLad to the environment
**Feature description:**

DataLad is a "data management and publication multitool".  Learn more by visiting http://datalad.org and even better http://handbook.datalad.org/ or listening to any [introductory talk on datalad like a recent debconf 2020]( https://saimei.ftp.acc.umu.se/pub/debian-meetings/2020/DebConf20/52-datalad-decentralized-management-of-digital-objects-for-open-science.webm) or slides from a [past presentation at MILA, Montreal](http://datasets.datalad.org/datalad/artwork/talks/2019-mila/#/) which was a little tuned for ML use-cases.

**Problem and motivation:**

DataLad solves many problems of version control, scalable access to remote data resources; growing amount of data is becoming available through git-annex (and thus DataLad): e.g. via http://datasets.datalad.org/ we provide access to over 200TB of (largely) neural data, and more to come!

### Why is this change important to you?

Disclaimer: I am "involved" in DataLad project ;-)

**Is this something you're interested in working on?**

I guess.  Although it might be just provision installation of DataLad within the ML workspace.  We provide Debian packages (in stock Debian and backports from http://neuro.debian.net), it is available from PyPI and also from conda-forge.  If ML is friendly to docker or singularity containers -- please also install   datalad-container  extension.

DataLad comes with command line and Python APIs.  So it should work nicely for Jupyter notebooks users to access the data they want or to establish version control of their results, or even reproducible (re)execution via [datalad run](http://handbook.datalad.org/en/latest/basics/basics-run.html)

### PR DESCRIPTION
**Pull request by yarikoptic**
It will also install git-annex which datalad uses for management of large
files.

Since it is just a "tool", I have not used --freeze-installed to benefit from
possible upgrades etc.

It could also be installed from stock ubuntu, but would be an older version.
Also backports are available from NeuroDebian, but I have decided to just go with
conda installation for now.

Closes #50

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [x] New Feature
- [ ] Feature Improvment
- [ ] Refactoring
- [ ] Documentation
- [ ] Other, please describe:

**Description:**

**Checklist:**

- [x] I have read the [CONTRIBUTING](https://github.com/ml-tooling/ml-workspace/blob/main/CONTRIBUTING.md) document.
- [ ] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Oh, I guess I should add to documentation. At large it should be just a reference to http://handbook.datalad.org/ and may be http://handbook.datalad.org/en/latest/code_from_chapters/usecase_ml_code.html and http://handbook.datalad.org/en/latest/beyond_basics/101-168-dvc.html in particular

**Comment by lukasmasuch** [comment]
@yarikoptic Thanks for the pull request! I took a closer look at datalab for the `0.12` release. Unfortunately, the installation is too big for a single tool to be preinstalled inside the main workspace flavor:

- conda install (409MB):
conda install

- apt install (390MB):
conda install

A few other options:
1. Build and publish your own datalad flavor:
```Dockerfile
# Extend from any of the workspace versions/flavors
FROM mltooling/ml-workspace:0.12.1

# Run you customizations, e.g.
RUN \
	# Install datalad
    apt-get update && \
    apt-get install -y datalad && \
    # Cleanup Layer - removes unneccessary cache files
    clean-layer.sh
```
2. Use an install method with a smaller footprint. However, since most space is used by git-annex, this might not be possible.
3. Add a tool installer script (e.g. see [these scripts](https://github.com/ml-tooling/ml-workspace/tree/main/resources/tools)). However, datalad is quite easy to install, so it might not need an additional installer script.

**Comment by yarikoptic** [comment]
`conda install (409MB)` -- is that in addition to what you already have installed otherwise anyways (  indeed would be too big then :-/) ?  majority should be common python packages (besides git-annex itself which is written in haskell but it should not pull too much).  I can look into it later to see where the hit comes from and see what could be done.

**Comment by lukasmasuch** [comment]
Yes, it's in addition. But there are some pinned dependencies that are forced to downgrade/upgrade... which might blow up the total required space as well. To see what's actually installed/removed/downgraded, you can just build this Dockerfile:

```Dockerfile
# Extend from any of the workspace versions/flavors
FROM mltooling/ml-workspace:0.12.1

# Run you customizations, e.g.
RUN \
	# Install datalad
    apt-get update && \
    apt-get install -y datalad && \
    # Cleanup Layer - removes unneccessary cache files
    clean-layer.sh
```

**Pull request closed without merging**
